# Imagem Base
FROM node:18

# COPIA OS ARQUIVOS PARA PASTA /app
COPY . /app

# DEFINE DIRETORIO PADRÃO PARA EXECUTAR OS COMANDOS
WORKDIR /app

# INSTALA DEPENDENCIAS
RUN npm install

# RODA COMANDO
CMD ["npm", "test"]
